config_filename: "default.yaml"
description: "Default LSTM model for copy task"

project_name: "copy_task"
ex_name: "ex01"

# model specific details

model:  "LSTM"
input_size: 8
output_size:  8
num_layers: 1
layer_size: [256]
activation: "tanh"
layer_norm: False
identity_init: False
use_relu: False
memory_size: 64
k: 4
phi_size: 256
r_size: 64

# optimization specific details

# Valid optimizer names: Adadelta, Adagrad, Adam, RMSprop, SGD
optim_name: "Adam"
lr: 1.0e-3
rho: 0.9
eps:  1.0e-8
weight_decay: 0.0
lr_decay: 0.0
beta_0: 0.9
beta_1: 0.999
alpha:  0.99
momentum: 0.0
centered: False
dampening:  0.0
nesterov: False
grad_clip_norm:  5.0

max_steps:  100000000
rseed:  5
device: "cuda" # can be cpu or cuda or cuda:1, cuda:2

# saving details
use_tflogger: True
save_every_n: 10000
